#!/bin/sh
#
# bootstrap
#
# Prepare test environment.

set -e

#
# Welcome to hubot-cookbook
#
echo ""
echo "  hubot-cookbook"
echo ""

#
# Check for Bundler
#
if test $(which bundle)
then
  echo "  + Bundler found."
else
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
fi

#
# Check for VirtualBox
#
if test ! $(which virtualbox)
then
  echo "  x You need to install VirtualBox."
  echo "    You can download it from https://www.virtualbox.org/wiki/Downloads"
  exit 1
else
  echo "  + VirtualBox found."
fi

#
# Check for Vagrant
#
if test ! $(which vagrant)
then
  echo "  x You need to install Vagrant."
  echo "    You can download it from http://www.vagrantup.com/downloads.html"
  exit 1
else
  echo "  + Vagrant found."
fi

#
# Add a Vagrant Box
#
if [[ $(vagrant box list) =~ opscode-ubuntu-12.04 ]]
then
  echo "  + Vagrant box 'opscode-ubuntu-12.04' found."
else
  echo "  + Adding vagrant box 'opscode-ubuntu-12.04'."
  vagrant box add opscode-ubuntu-12.04 \
    https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
fi

#
# Install vagrant plugin
#
if [[ $(vagrant plugin list) =~ vagrant-berkshelf ]]
then
  echo "  + Vagrant plugin 'vagrant-berkshelf' found."
else
  echo "  + Installing vagrant plugin 'vagrant-berkshelf'."
  vagrant plugin install vagrant-berkshelf
fi

#
# Install Gems
# 
echo "  + Bootstrapping your Rubies."
bundle install --quiet

#
# Install busser plugin 'serverspec'
#
echo "  + Installing busser plugin 'serverspec'."
busser plugin install serverspec

#
# Setup kitchen.yml
#
if test -f .kitchen.yml
then
  echo "  + .kitchen.yml found."
else
  echo "  - You need .kitchen.yml for testing."
  echo "  + Setuping kitchen.yml"
  cp .kitchen.yml.sample .kitchen.yml

  printf "  ? data bags directory path: "
  read -e data_bags_path
  data_bags_path=`echo $data_bags_path | sed -e 's/\//\\\\\//g'`
  gsed -i "s/DATA_BAGS_PATH/$data_bags_path/g" .kitchen.yml

  printf "  ? encrypted_data_bag_secret file path: "
  read -e encrypted_data_bag_secret_path
  encrypted_data_bag_secret_path=`echo $encrypted_data_bag_secret_path | sed -e 's/\//\\\\\//g'`
  gsed -i "s/ENCRYPTED_DATA_BAG_SECRET_KEY_PATH/$encrypted_data_bag_secret_path/g" .kitchen.yml

  printf "  ? hubot git repository (use ssh clone url): "
  read -e hubot_repo
  hubot_repo=`echo $hubot_repo | sed -e 's/\//\\\\\//g'`
  gsed -i "s/HUBOT_REPO/$hubot_repo/g" .kitchen.yml

  echo "  + Created .kitchen.yml."
fi

#
# Startup Instructions
#
echo ""
echo "  Good work. We're ready."

exit 0
