#!/bin/sh
#
# bootstrap
#
# Prepare test environment.

set -e

#
# Welcome to hubot-cookbook
#
echo ""
echo "  hubot-cookbook"
echo ""

#
# Check for Bundler
#
if test $(which bundle)
then
  echo "  + Bundler found."
else
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle install --quiet

#
# Setup kitchen.yml
#
if test -f .kitchen.yml
then
  echo "  + .kitchen.yml found."
else
  echo "  - You need .kitchen.yml for testing."
  echo "  + Setuping kitchen.yml"
  cp .kitchen.yml.sample .kitchen.yml

  printf "  ? data bags directory path: "
  read -e data_bags_path
  data_bags_path=`echo $data_bags_path | sed -e 's/\//\\\\\//g'`
  gsed -i "s/DATA_BAGS_PATH/$data_bags_path/g" .kitchen.yml

  printf "  ? encrypted_data_bag_secret file path: "
  read -e encrypted_data_bag_secret_path
  encrypted_data_bag_secret_path=`echo $encrypted_data_bag_secret_path | sed -e 's/\//\\\\\//g'`
  gsed -i "s/ENCRYPTED_DATA_BAG_SECRET_KEY_PATH/$encrypted_data_bag_secret_path/g" .kitchen.yml

  printf "  ? hubot git repository (use ssh clone url): "
  read -e hubot_repo
  hubot_repo=`echo $hubot_repo | sed -e 's/\//\\\\\//g'`
  gsed -i "s/HUBOT_REPO/$hubot_repo/g" .kitchen.yml

  echo "  + Created .kitchen.yml."
fi

#
# Startup Instructions
#
echo ""
echo "  Good work. We're ready."

exit 0
